# Generated by Django 4.1.5 on 2023-01-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원'},
        ),
        migrations.AlterModelTable(
            name='member',
            table='shinhan_member',
        ),
    ]
