# Generated by Django 4.1.5 on 2023-01-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='member',
        ),
    ]
